name: CI
on:
  workflow_dispatch:
  pull_request:
    type:
      - opened
      - synchronize

  push:
    branches:
      - main
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --immutable

      - name: Run ESLint
        run: npm run lint

      - name: Print current date
        run: |
          echo "Сьогоднішня дата: $(date)"
          echo "Дата виведена успішно!"